SELECT * FROM customer_shopping LIMIT 10

-------------------------------------- Questions ----------------------------------------------------

-- 1) What is the total revenue generated by male vs female customer?

SELECT gender,
	   SUM(purchase_amount) AS total_revenue 
FROM customer_shopping
GROUP BY gender;

-- 2) Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount 
FROM customer_shopping
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount)
FROM customer_shopping
);

-- 3) Which are the top 5 products with the highest average review rating?

SELECT item_purchased, Round(AVG (review_rating::numeric),2) AS average_product_rating
FROM customer_shopping
GROUP BY item_purchased
ORDER BY average_product_rating DESC
LIMIT 5
















